[package]
name = "motorguard-groups"
version = "0.1.0"
edition = "2021"

[dependencies]
motorguard-core = { path = "../core" }
motorguard-database = { path = "../database" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
futures-util = { workspace = true }
futures = { workspace = true }
